version: "3.2"
services:
  flask:
    build: .
    ports:
      - 80:8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      QR_CODE_DEFAULT_URL: 'https://hub.docker.com/r/iamabhishekt98/qrcode'
      QR_CODE_DEFAULT_FILE_NAME: 'docker_hub.png'
    volumes:
      - .:/home/myuser
  ubuntu:
    image: iamabhishekt98/myubuntuimage
    stdin_open: true # docker run -i
    tty: true        # docker run -t